"""
Django settings for Mohami_dz project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import datetime
import jwt

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!x4%0o$$&@b46&mu(_%x@=q(jk$%49!rz7gl8tf)2p+5&uy%-l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','http://localhost:3000/?']


# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'rest_framework.authtoken',
    'knox',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'corsheaders',
    'django.contrib.staticfiles',
    'accueil.apps.AccueilConfig',
    'login.apps.LoginConfig',
    'avocat.apps.AvocatConfig',
    'register.apps.RegisterConfig',
    'appointment.apps.AppointmentConfig',
    'search.apps.SearchConfig',
    'logout.apps.LogoutConfig'
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware', 
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Mohami_dz.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'accueil/Client/build'),
                 os.path.join(BASE_DIR,'login/Client/build'),
                 os.path.join(BASE_DIR,'register/Client/build'),
                 os.path.join(BASE_DIR,'appointment/Client/build'),
                 os.path.join(BASE_DIR,'login/Client2/build'),
                 os.path.join(BASE_DIR,'register/Client2/build'),
                 os.path.join(BASE_DIR,'search/Client/build'),
                 os.path.join(BASE_DIR,'search/Client2/build'),
                 os.path.join(BASE_DIR,'accueil/Client2/build'),
                 os.path.join(BASE_DIR,'search/Client3/build'),
                 os.path.join(BASE_DIR,'avocat/Client/build'),
                 os.path.join(BASE_DIR,'search/Client4/build'),
                 os.path.join(BASE_DIR,'search/Client5/build')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Mohami_dz.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS=[ os.path.join(BASE_DIR,'accueil/Client/build/static'),
                  os.path.join(BASE_DIR,'login/Client/build/static'),
                  os.path.join(BASE_DIR,'register/Client/build/static'),
                  os.path.join(BASE_DIR,'login/Client2/build/static'),
                  os.path.join(BASE_DIR,'register/Client2/build/static'),
                  os.path.join(BASE_DIR,'search/Client/build/static'),
                  os.path.join(BASE_DIR,'search/Client2/build/static'),
                  os.path.join(BASE_DIR,'accueil/Client2/build/static'),
                  os.path.join(BASE_DIR,'search/Client3/build/static'),
                  os.path.join(BASE_DIR,'avocat/Client/build/static'),
                  os.path.join(BASE_DIR,'search/Client4/build/static'),
                  os.path.join(BASE_DIR,'search/Client5/build/static'),]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]
JWT_SECRET_KEY = 'Mascula@dz.2000'
JWT_ALGORITHM = 'HS256'
JWT_EXP_DELTA_SECONDS = 3600


MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
MEDIA_URL = '/media/'