# Generated by Django 5.0 on 2024-01-03 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Only letters are allowed.', regex='^[A-Za-z ]*$')])),
                ('last_name', models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Only letters are allowed.', regex='^[A-Za-z ]*$')])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('speciality', models.CharField(default='', max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
