# Generated by Django 5.0 on 2024-01-03 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_lawyer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='phone_number',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must start with 05, 06, or 07 and be 10 digits long.', regex='^(05|06|07)[0-9]{8}$'), django.core.validators.MinLengthValidator(limit_value=10), django.core.validators.MaxLengthValidator(limit_value=10)]),
        ),
    ]
