# Generated by Django 5.0 on 2024-01-03 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_lawyer_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Only letters are allowed.', regex='^[A-Za-z ]*$')])),
                ('last_name', models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Only letters are allowed.', regex='^[A-Za-z ]*$')])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
            ],
        ),
        migrations.AddField(
            model_name='lawyer',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
