# Generated by Django 5.0 on 2024-01-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_user_lawyer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
