# Generated by Django 5.0 on 2024-01-03 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer',
            name='description',
        ),
    ]
