# Generated by Django 5.0 on 2024-01-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_remove_lawyer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='location',
            field=models.CharField(default='', max_length=20),
        ),
    ]
