# Generated by Django 5.0 on 2024-01-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_lawyer_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
