# Generated by Django 5.0 on 2024-01-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_remove_lawyer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
