# Generated by Django 5.0 on 2024-01-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_user_is_active_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
