# Generated by Django 5.0 on 2024-01-06 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0012_lawyer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=10, null=True)),
                ('day', models.CharField(blank=True, max_length=20, null=True)),
                ('accepted_yet', models.BooleanField(blank=True, default='False', null=True)),
                ('lawyerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.lawyer')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.user')),
            ],
        ),
    ]
