# Generated by Django 5.0 on 2024-01-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='note',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
